spring.application.name=movie-watchlist-api
spring.datasource.url=jdbc:postgresql://localhost:5432/movie_watchlist
spring.datasource.username=postgres
spring.datasource.password=postgres
omdb.api.url=http://www.omdbapi.com/
omdb.api.key=263579c3

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
